# roles/devs/tasks/git.yml
---
- name: Git | Configurar Git, aliases y hooks para el usuario
  tags: git
  become: true
  become_user: "{{ remote_regular_user }}"
  block:
    - name: Git | Aplicar configuración global (.gitconfig)
      community.general.git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
      loop: "{{ developer_git_config_settings }}"

    - name: Git | Crear directorio para hooks globales
      ansible.builtin.file:
        path: "{{ developer_git_hooks_path }}"
        state: directory
        mode: '0755'

    - name: Git | Copiar script de hook genérico a múltiples destinos
      ansible.builtin.copy:
        src: default_hook.sh
        dest: "{{ developer_git_hooks_path }}/{{ item }}"
        mode: "0755"
      loop: "{{ developer_git_generic_hook_list }}"

    - name: Git | Copiar script de hook 'pre-push'
      ansible.builtin.copy:
        src: pre-push
        dest: "{{ developer_git_hooks_path }}/pre-push"
        mode: "0755"

    - name: Git | Copiar archivo de prompt personalizado
      ansible.builtin.copy:
        src: .prompt_git
        dest: "/home/{{ remote_regular_user }}/.prompt_git"
        mode: "0644"
