---
- name: Paquetes Dev | Instalar herramientas de terminal y editores
  tags: packages_dev
  become: true
  ansible.builtin.apt:
    name: "{{ developer_packages_base }}"
    state: present
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"
