---
- name: Rancher CLI | Instalar y configurar la CLI de Rancher
  tags: rancher
  become: true
  block:
    - name: Rancher CLI | Verificar si el binario ya está instalado
      ansible.builtin.stat:
        path: /usr/local/bin/rancher
      register: developer_rancher_cli

    - name: Rancher CLI | Instalar la última versión
      when: not developer_rancher_cli.stat.exists
      block:
        - name: Rancher CLI | Obtener la URL de la última versión
          ansible.builtin.uri:
            url: "https://api.github.com/repos/{{ developer_rancher_cli_repo }}/releases/latest"
            return_content: true
          register: developer_json_response

        - name: Rancher CLI | Extraer URL del asset
          ansible.builtin.set_fact:
            developer_rancher_asset_url: >-
              {{ (developer_json_response.json.assets
                  | selectattr('name', 'search', '^rancher-linux-amd64.*\\.tar\\.gz$')
                  | list
                  | first).browser_download_url }}

        - name: Rancher CLI | Descargar y extraer el binario en un solo paso
          ansible.builtin.unarchive:
            remote_src: true
            src: "{{ developer_rancher_asset_url }}"
            dest: "/usr/local/bin/"
            extra_opts:
              - "--strip-components=1"
            owner: root
            group: root
            mode: "0755"

    - name: Rancher CLI | Crear enlace simbólico 'rancher2' para compatibilidad
      ansible.builtin.file:
        src: /usr/local/bin/rancher
        dest: /usr/local/bin/rancher2
        state: link
        force: true
