---
- name: Rancher CLI | Instalar y configurar la CLI de Rancher
  tags: rancher
  become: true
  block:
    - name: Rancher CLI | Verificar si el binario ya está instalado
      ansible.builtin.stat:
        path: /usr/local/bin/rancher
      register: devs_rancher_cli

    - name: Rancher CLI | Instalar la última versión
      when: not devs_rancher_cli.stat.exists
      block:
        - name: Rancher CLI | Obtener la URL de la última versión
          ansible.builtin.uri:
            url: "https://api.github.com/repos/{{ devs_rancher_cli_repo }}/releases/latest"
            return_content: true
          register: json_response

        - name: Rancher CLI | Descargar y extraer el binario en un solo paso
          ansible.builtin.unarchive:
            remote_src: true
            src: "{{ (json_response.json.assets | selectattr('name', 'search', '^rancher-linux-amd64.*\\.tar\\.gz$') | list | first).browser_download_url }}"
            dest: "/usr/local/bin/"
            extra_opts:
              - "--strip-components=1"
            owner: root
            group: root
            mode: "0755"

    - name: Rancher CLI | Crear enlace simbólico 'rancher2' para compatibilidad
      ansible.builtin.file:
        src: /usr/local/bin/rancher
        dest: /usr/local/bin/rancher2
        state: link
        force: true

    - name: Rancher CLI | Añadir autocompletado de bash para el usuario
      become_user: "{{ remote_regular_user }}"
      ansible.builtin.blockinfile:
        path: "/home/{{ remote_regular_user }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - RANCHER COMPLETION"
        block: |
          if command -v rancher >/dev/null 2>&1; then
            source <(rancher completion bash)
          fi
