---
- name: SSH | Configurar el directorio y las claves del usuario
  tags: ssh
  become: true
  become_user: "{{ remote_regular_user }}"
  block:
    - name: SSH | Asegurar que el directorio .ssh existe con los permisos correctos
      ansible.builtin.file:
        path: "/home/{{ remote_regular_user }}/.ssh"
        state: directory
        mode: "0700"

    - name: SSH | Generar clave SSH si no existe
      community.crypto.openssh_keypair:
        path: "{{ developer_ssh_config.key_path }}"
        type: "{{ developer_ssh_config.key_type }}"
        size: "{{ developer_ssh_config.key_size }}"
        state: present
        mode: "0600"

    - name: SSH | Desplegar la plantilla de configuración .ssh/config
      ansible.builtin.template:
        src: "{{ developer_ssh_config.config_template_src }}"
        dest: "/home/{{ remote_regular_user }}/.ssh/config"
        mode: "0600"
