---
# Requiere login previo con github
- name: Infra - Clonar projecto terraform
  become: false
  ansible.builtin.git:
    repo: git@github.com:adhoc-dev/InfraR2.git
    dest: /home/{{ remote_regular_user }}/infra_nubeadhoc
    version: main
    clone: true
    update: true
