---
- name: Converge
  hosts: all
  become: true

  vars:
    # Deshabilitar tareas de GUI que no funcionan en Docker
    skip_gnome_tasks: true

  pre_tasks:
    # Simular que estamos corriendo con sudo
    - name: Converge | Simulate sudo invocation (SUDO_USER) for the role  # noqa: var-naming[no-role-prefix]
      ansible.builtin.set_fact:
        ansible_facts: "{{ ansible_facts | combine({'env': {'SUDO_USER': 'testuser'}}, recursive=True) }}"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false

    - name: Install basic dependencies for testing
      ansible.builtin.apt:
        name:
          - sudo
          - gnupg
          - lsb-release
          - dbus
        state: present

  roles:
    - role: funcional
