---
# Usuario genérico para ejecutar algunas tareas
remote_regular_user: "{{ ansible_env.SUDO_USER }}"

packages_system:
  - htop
  - mc
  - tmux
  - apt-transport-https
  - curl
  - wget
  - openssh-client
  - openssh-server
  - jq
  - tldr
  - locate
  - libxshmfence1

packages_compression:
  - zip
  - gzip
  - tar
  - unzip
  - p7zip-full

packages_apps:
  - poedit
  - fail2ban
  - ufw
  - vlc
  - ffmpeg

packages_hardware_analysis:
  - inxi
  - hwinfo
  - glances
  - mtr
  - hardinfo
  - stacer
  - screenfetch

packages_gui_utils:
  - alacarte
  - fonts-firacode
  - flameshot
  - fprintd
  - libpam-fprintd
  - fido2-tools

# Paquetes específicos para Ubuntu
packages_ubuntu_only:
  - tlp
  - tlp-rdw
  - acpi-call-dkms
  - powertop
  - preload
  - bleachbit
  - ubuntu-restricted-extras
  - ppa-purge
  - unrar
  - p7zip-rar

# Lista de paquetes a ser eliminados
packages_to_remove:
  - indicator-multiload
  - thunderbird
  - rhythmbox
  - remmina
  - gnome-games
  - gnome-maps
  - gnome-weather
  - gnome-calendar

# Lista de configuraciones de dconf para el entorno de escritorio
dconf_settings:
  # Workspace Matrix
  - { key: "/org/gnome/shell/extensions/wsmatrix/num-columns", value: "2" }
  - { key: "/org/gnome/shell/extensions/wsmatrix/num-rows", value: "2" }
  - { key: "/org/gnome/shell/extensions/wsmatrix/show-overview-grid", value: "true" }
  # OpenWeather
  - { key: "/org/gnome/shell/extensions/openweather/city", value: "'-32.9575, -60.639444>Rosario, Santa Fe>-1'" }
  - { key: "/org/gnome/shell/extensions/openweather/unit", value: "'celsius'" }
  - { key: "/org/gnome/shell/extensions/openweather/wind-speed-unit", value: "'m/s'" }
  - { key: "/org/gnome/shell/extensions/openweather/pressure-unit", value: "'hPa'" }
  # Dash to Dock
  - { key: "/org/gnome/shell/extensions/dash-to-dock/scroll-action", value: "'cycle-windows'" }
  - { key: "/org/gnome/shell/extensions/dash-to-dock/isolate-workspaces", value: "true" }
  - { key: "/org/gnome/shell/extensions/dash-to-dock/multi-monitor", value: "true" }
  # Preferencias de GNOME
  - { key: "/org/gnome/shell/window-switcher/current-workspace-only", value: "true" }
  - { key: "/org/gnome/shell/app-switcher/current-workspace-only", value: "true" }
  - { key: "/org/gnome/desktop/interface/clock-show-date", value: "true" }
  - { key: "/org/gnome/desktop/interface/show-battery-percentage", value: "true" }
  # Configuración de espacios de trabajo fijos (el punto a discutir)
  - { key: "/org/gnome/mutter/dynamic-workspaces", value: "false" }
  - { key: "/org/gnome/desktop/wm/preferences/num-workspaces", value: "4" }
