---
# Usuario genérico para ejecutar algunas tareas
remote_regular_user: "{{ ansible_env.SUDO_USER }}"

# Extensiones predefinidas para devs
vscode_extension_list_devs:
  # Install Visual Studio Code extensions.
  - ms-python.python
  # Markdown linting and style checking for Visual Studio Code
  - DavidAnson.vscode-markdownlint
  # Supercharge the Git capabilities built into Visual Studio Code
  - eamodio.gitlens
  # Odoo snippets
  - mstuttgart.odoo-snippets
  # Check spell (En & Es)
  - streetsidesoftware.code-spell-checker
  - streetsidesoftware.code-spell-checker-spanish
  # Odoo IDE (https://marketplace.visualstudio.com/items?itemName=trinhanhngoc.vscode-odoo)
  - trinhanhngoc.vscode-odoo
  # Kubernetes extension
  - ms-kubernetes-tools.vscode-kubernetes-tools
  # Remote containers
  - ms-vscode-remote.remote-containers
  # Remote development
  - ms-vscode-remote.vscode-remote-extensionpack
