---
- name: Tareas previas al deploy de roles
  hosts: laptop
  tags: always
  become: true
  gather_facts: false
  pre_tasks:
    - name: Actualizar caché
      tags: always
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

- name: Deploy funcional role
  hosts: laptop
  tags: funcional
  become: true
  gather_facts: true
  roles:
    - funcional

- name: Deploy devs role
  hosts: laptop
  tags: devs
  gather_facts: true
  become: true
  roles:
    - devs

- name: Deploy sysadmin role
  hosts: laptop
  tags: sysadmin
  gather_facts: true
  become: true
  roles:
    - sysadmin

- name: Deploy deploy role
  hosts: laptop
  tags: deploy
  gather_facts: true
  become: true
  roles:
    - deploy

- name: Completar deploy y limpiar caché
  hosts: laptop
  become: true
  tasks:
    - name: Cleanup package cache (debian and ubuntu)
      tags: always
      ansible.builtin.apt:
        autoclean: true
      changed_when: false

    - name: Autoremove orphan packages (debian and ubuntu)
      tags: always
      ansible.builtin.apt:
        autoremove: true
        purge: true

# agregar cron y pull para update automático
#  - name: Agregar ansible-pull cron job
#    cron:
#      name: ansible auto-provision
#      user: "{{ remote_regular_user }}"
#      minute: "*/10"
#      job: ansible-pull -o -U https://github.com/adhoc-dev/ansible.git
