---
- name: Tareas previas al deploy de roles
  hosts: laptop
  tags: always
  become: true

  vars:
    target_profile: "{{ profile_override | default('funcional') }}"

  pre_tasks:
    - name: Actualizar caché
      tags: always
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
    - name: Definir el perfil de provisionamiento
      ansible.builtin.set_fact:
        target_profile: "{{ target_profile | default('funcional') }}"

  roles:
    - role: "{{ target_profile }}"

    - role: deploy
      tags: deploy

  post_tasks:
    - name: Limpiar paquetes huérfanos y caché
      tags: always
      ansible.builtin.apt:
        autoremove: true
        purge: true
        autoclean: true
      changed_when: false
