---
- name: Tareas previas al deploy de roles
  hosts: laptop
  become: true

  vars:
    target_profile: "{{ profile_override | default('funcional') }}"

  # --- TAREAS PREVIAS ---
  pre_tasks:
    - name: "Asegurar que /tmp tenga los permisos correctos (1777)"
      tags: always
      ansible.builtin.file:
        path: /tmp
        state: directory
        mode: '1777'

    - name: Actualizar caché de paquetes
      tags: always # Se ejecuta siempre, incluso si filtras por otras etiquetas.
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

  # --- SECCIÓN DE ROLES ---
  roles:
    # Este rol se ejecuta por defecto o según la variable. NO está etiquetado.
    - role: "{{ target_profile }}"

    # Este rol SOLO se ejecuta si se pide explícitamente la etiqueta 'deploy'.
    - role: deploy
      tags: deploy

  # --- TAREAS POSTERIORES ---
  post_tasks:
    - name: Limpiar paquetes huérfanos y caché
      tags: always # Se ejecuta siempre.
      ansible.builtin.apt:
        autoremove: true
        purge: true
        autoclean: true
      changed_when: false
