---
- name: SysAdmin - Instalar gcloud cli
  tags: gcloud
  become: true
  block:

    - name: Asegurar que el directorio para keyrings de APT existe
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Descargar y guardar la llave GPG de Google Cloud
      ansible.builtin.shell: >
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg |
        gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
      args:
        creates: /usr/share/keyrings/cloud.google.gpg
      changed_when: false

    - name: Agregar el repositorio de Google Cloud SDK
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
        state: present
        filename: google-cloud-sdk
        update_cache: true

    - name: Instalar google-cloud-sdk
      ansible.builtin.apt:
        name: google-cloud-sdk
        state: present
