---
- name: SysAdmin - Instalar gcloud cli
  tags: gcloud
  become: true
  block:

    - name: Asegurar que el directorio para keyrings de APT existe
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Descargar y guardar la llave GPG de Google Cloud
      ansible.builtin.get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /tmp/gcloud-apt-key.gpg
        mode: '0644'

    - name: Convertir y mover la llave GPG
      ansible.builtin.shell: |
        set -o pipefail
        gpg --dearmor < /tmp/gcloud-apt-key.gpg > /usr/share/keyrings/cloud.google.gpg
      args:
        creates: /usr/share/keyrings/cloud.google.gpg
      changed_when: false

    - name: Limpiar archivo temporal de llave GPG
      ansible.builtin.file:
        path: /tmp/gcloud-apt-key.gpg
        state: absent

    - name: Agregar el repositorio de Google Cloud SDK
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
        state: present
        filename: google-cloud-sdk
        update_cache: true

    - name: Instalar google-cloud-sdk
      ansible.builtin.apt:
        name: google-cloud-sdk
        state: present
