---
- name: SysAdmin - Instalar gcloud cli
  tags: gcloud
  become: true
  block:
    - name: Crear el directorio /usr/share/keyrings si no existe
      file:
        path: /usr/share/keyrings
        state: directory
        mode: "0755"

    - name: Descargar y almacenar la llave GPG de Google Cloud SDK
      ansible.builtin.shell: |
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
      args:
        creates: /usr/share/keyrings/cloud.google.gpg

    - name: Agregar el repositorio de Google Cloud SDK
      copy:
        content: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main\n"
        dest: /etc/apt/sources.list.d/google-cloud-sdk.list
        mode: "0644"

    - name: Actualizar el índice de paquetes de apt
      apt:
        update_cache: yes

    - name: Instalar google-cloud-sdk
      apt:
        name: google-cloud-sdk
        state: present
