---
- name: SysAdmin - Plugins para kubectl
  tags: kubectl_plugins
  block:
    - name: Copiar Installer
      copy:
        src: files/install_gh_bin.sh
        dest: /tmp/install_gh_bin.sh
        mode: "0774"

    - name: Execute Installer
      command: /tmp/install_gh_bin.sh
      become: true

    - name: Instalar kubectx
      when: ansible_facts['distribution'] == 'Debian'
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - kubens
          - kubectx

    # # https://github.com/derailed/popeye
    # - name: popeye - Descargar binario y extraer

    #   unarchive:
    #     src: https://github.com/derailed/popeye/releases/download/v0.21.3/popeye_linux_amd64.tar.gz
    #     dest: /tmp/
    #     owner: "{{ remote_regular_user }}"
    #     group: "{{ remote_regular_user }}"
    #     mode: "774"
    #     remote_src: true

    # - name: popeye - Mover binario al path
    #   copy:
    #     src: /tmp/popeye
    #     dest: /usr/bin/
    #     owner: "{{ remote_regular_user }}"
    #     group: "{{ remote_regular_user }}"
    #     mode: "774"

    # # https://github.com/robscott/kube-capacity
    # - name: kube-capacity - Descargar binario y extraer
    #   unarchive:
    #     src: https://github.com/robscott/kube-capacity/releases/download/v0.8.0/kube-capacity_v0.8.0_linux_x86_64.tar.gz
    #     dest: /tmp/
    #     owner: "{{ remote_regular_user }}"
    #     group: "{{ remote_regular_user }}"
    #     mode: "774"
    #     remote_src: true

    # - name: kube-capacity - Mover binario al path
    #   copy:
    #     src: /tmp/kube-capacity
    #     dest: /usr/bin/
    #     owner: "{{ remote_regular_user }}"
    #     group: "{{ remote_regular_user }}"
    #     mode: "774"

    # - name: kubectx - Clonar projecto kubectx
    #   unarchive:
    #     src: https://github.com/ahmetb/kubectx/releases/download/v0.9.5/kubectx_v0.9.5_linux_x86_64.tar.gz
    #     dest: /tmp/
    #     owner: "{{ remote_regular_user }}"
    #     group: "{{ remote_regular_user }}"
    #     mode: "774"
    #     remote_src: true

    # - name: kubectx - Mover binario al path
    #   copy:
    #     src: /tmp/kubectx
    #     dest: /usr/bin/
    #     owner: "{{ remote_regular_user }}"
    #     group: "{{ remote_regular_user }}"
    #     mode: "774"

    # # https://github.com/rancher/rke
    # - name: rke - Descargar binario y extraer
    #   get_url:
    #     url: https://github.com/rancher/rke/releases/download/v1.6.1/rke_linux-amd64
    #     dest: /tmp/
    #     owner: "{{ remote_regular_user }}"
    #     group: "{{ remote_regular_user }}"
    #     mode: "774"

    # - name: rke - Mover binario al path
    #   copy:
    #     src: /tmp/rke_linux-amd64
    #     dest: /usr/bin/rke
    #     owner: "{{ remote_regular_user }}"
    #     group: "{{ remote_regular_user }}"
    #     mode: "774"

    # # https://github.com/FairwindsOps/pluto
    # - name: pluto - Descargar binario y extraer
    #   unarchive:
    #     src: https://github.com/FairwindsOps/pluto/releases/download/v5.20.1/pluto_5.20.1_linux_amd64.tar.gz
    #     dest: /tmp/
    #     owner: "{{ remote_regular_user }}"
    #     group: "{{ remote_regular_user }}"
    #     mode: "774"
    #     remote_src: true

    # - name: pluto - Mover binario al path
    #   copy:
    #     src: /tmp/pluto
    #     dest: /usr/bin/
    #     owner: "{{ remote_regular_user }}"
    #     group: "{{ remote_regular_user }}"
    #     mode: "774"
