---
- name: SysAdmin - Plugins para kubectl
  tags: kubectl_plugins
  block:
    - name: "Instalar cada plugin según su tipo"
      # Incluimos el archivo de tareas y le pasamos cada 'plugin' del bucle
      include_tasks: "{{ role_path }}/tasks/install_single_plugin.yml"
      loop: "{{ kubectl_plugins_list }}"
      loop_control:
        loop_var: plugin # Le decimos al loop que cada item se llama 'plugin'

    - name: "Configurar autocompletado para todos los plugins"
      become: false # Se ejecuta como el usuario normal
      ansible.builtin.blockinfile:
        path: "/home/{{ remote_regular_user }}/.bashrc"
        owner: "{{ remote_regular_user }}"
        group: "{{ remote_regular_user }}"
        create: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK - KUBE PLUGINS COMPLETION"
        block: |
          {% for p in kubectl_plugins_list | selectattr('completion', 'defined') %}
          if command -v {{ p.name }} > /dev/null; then
            {{ p.completion }}
          fi
          {% endfor %}
