---
- name: SysAdmin | Instalar paquetes base
  tags: packages_sysadmin
  become: true
  ansible.builtin.apt:
    name: "{{ sysadmin_packages_base }}"
    state: present
    update_cache: true

- name: SysAdmin | Instalar Timeshift y dependencias (solo Debian)
  tags: packages_sysadmin
  become: true
  ansible.builtin.apt:
    name: "{{ sysadmin_packages_timeshift }}"
    state: present
  when: ansible_facts['distribution'] == 'Debian'
