---
- name: SysAdmin - Instalación paquetes y dependencias varias
  tags: packages_sysadmin
  block:
    - name: Instalar paquetes y dependencias
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - kubecolor
