---
- name: SysAdmin - Instalar apps mensajería (social)
  block:
    - name: Social - Instalar telegram desktop
      become: true
      apt:
        name: telegram-desktop
        state: present

    - name: Social - Instalar discord
      snap:
        name:
          - discord
  tags: social
