---
- name: VirtualBox - Instalar app y sus dependencias en Debian 12
  become: true
  when: ansible_facts['distribution'] == 'Debian'
  block:

    - name: Asegurar que el directorio para keyrings de APT existe
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Descargar y guardar la llave GPG de Oracle VirtualBox
      ansible.builtin.shell: >
        curl -fsSL https://www.virtualbox.org/download/oracle_vbox_2016.asc |
        gpg --dearmor -o /usr/share/keyrings/oracle-virtualbox-2016.gpg
      args:
        # Esto asegura que la llave solo se descargue una vez
        creates: /usr/share/keyrings/oracle-virtualbox-2016.gpg
      changed_when: false

    - name: Añadir el repositorio de VirtualBox
      ansible.builtin.apt_repository:
        # El cambio clave: apuntamos explícitamente a la llave que acabamos de guardar
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
        state: present
        filename: virtualbox
        update_cache: true

    # Consolidamos la instalación de todos los paquetes en una sola tarea.
    - name: Instalar dependencias, kernel headers y VirtualBox
      ansible.builtin.apt:
        name:
          - curl
          - wget
          - gnupg2
          - lsb-release
          - "linux-headers-{{ ansible_kernel }}" # Usa el fact del kernel actual
          - dkms
          - virtualbox-7.0
        state: present

    - name: Añadir usuario regular al grupo 'vboxusers'
      ansible.builtin.user:
        name: "{{ remote_regular_user }}"
        groups: vboxusers
        append: yes
