---
- name: SysAdmin | Instalar y configurar VirtualBox
  tags: virtualbox
  become: true
  when:
    - ansible_facts['os_family'] == 'Debian'
    - not (ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_release'] == 'trixie')
  block:
    - name: VirtualBox | Instalar prerrequisitos y headers del kernel
      ansible.builtin.apt:
        name: "{{ sysadmin_vbox_prereqs + ['linux-headers-' + ansible_kernel] }}"
        state: present
        update_cache: true

    - name: VirtualBox | Añadir la clave GPG de Oracle
      ansible.builtin.shell: "curl -fsSL {{ sysadmin_vbox_gpg_url }} | gpg --dearmor -o {{ sysadmin_vbox_gpg_path }}"
      args:
        creates: "{{ sysadmin_vbox_gpg_path }}"
      changed_when: false

    - name: VirtualBox | Añadir el repositorio de APT de Oracle
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by={{ sysadmin_vbox_gpg_path }}] https://download.virtualbox.org/virtualbox/debian {{ 'bookworm' if ansible_facts['distribution'] == 'Debian' else ansible_distribution_release }} contrib"
        state: present
        filename: virtualbox
        update_cache: true

    - name: VirtualBox | Instalar el paquete de VirtualBox
      ansible.builtin.apt:
        name: "{{ sysadmin_vbox_package }}"
        state: present

    - name: VirtualBox | Añadir usuario al grupo 'vboxusers'
      ansible.builtin.user:
        name: "{{ remote_regular_user }}"
        groups: vboxusers
        append: true
