---
- name: SysAdmin | Instalar VirtualBox
  tags: virtualbox
  become: true
  when: ansible_facts['distribution'] == 'Debian'
  block:
    - name: VirtualBox | Asegurar que el repositorio de Oracle esté eliminado
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
        state: absent
    - name: VirtualBox | Asegurar que la clave GPG de Oracle esté eliminada
      ansible.builtin.file:
        path: /usr/share/keyrings/oracle-virtualbox-2016.gpg
        state: absent

    - name: VirtualBox | Habilitar los componentes 'contrib' y 'non-free'
      ansible.builtin.apt_repository:
        repo: "deb http://deb.debian.org/debian/ {{ ansible_distribution_release }} main contrib non-free-firmware"
        state: present
        filename: 'debian-main-components'
        update_cache: true

    - name: VirtualBox | Instalar paquetes de VirtualBox y dependencias
      ansible.builtin.apt:
        name: "{{ sysadmin_virtualbox_packages + ['linux-headers-' + ansible_kernel] }}"
        state: present

    - name: VirtualBox | Añadir usuario al grupo 'vboxusers'
      ansible.builtin.user:
        name: "{{ remote_regular_user }}"
        groups: vboxusers
        append: true
