---
- name: zsh - Instalar y setear por default
  block:
    - name: zsh - Instalar
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - zsh
          - zsh-autosuggestions
          - zsh-syntax-highlighting
          - fonts-powerline

    - name: zsh - Enlace simbólico de archivo de configuración
      command: ln -sf ./files/.zshrc /home/{{ remote_regular_user }}/.zshrc

    - name: zsh - Set as default
      become: true
      shell: chsh -s $(which zsh) "{{ remote_regular_user }}"
  tags: zsh

- name: omz y plugins varios
  tags: omz
  block:
    # https://github.com/ohmyzsh/ohmyzsh
    - name: omz - Descargar script
      become_user: "{{ remote_regular_user }}"
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/omz_install.sh
        mode: "+x"
        force: true

    - name: omz - Instalar
      become_user: "{{ remote_regular_user }}"
      script: /tmp/omz_install.sh --force

    # https://github.com/atuinsh/atuin
    - name: Download Atuin install script
      get_url:
        url: https://raw.githubusercontent.com/atuinsh/atuin/main/install.sh
        dest: /tmp/atuin_install.sh
        mode: "0755" # This sets the script as executable
        force: true
      check_mode: no # Ensures the task runs even in check mode

    - name: Install Atuin
      become: true # Only use 'become' if necessary
      become_user: "{{ remote_regular_user }}"
      shell: /tmp/atuin_install.sh --force --git atuinsh/atuin
      args:
        executable: /bin/bash # Ensures that bash is used for running the script

    - name: omz - Clonar varios plugins
      git:
        repo: "{{ item.key }}"
        dest: "{{ item.value }}"
        clone: yes
        update: yes
      with_items:
        - {
            key: "https://github.com/zsh-users/zsh-syntax-highlighting.git",
            value: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting",
          }
        - {
            key: "https://github.com/zsh-users/zsh-autosuggestions",
            value: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions",
          }
        - {
            key: "https://github.com/zsh-users/zsh-completions",
            value: "~/.oh-my-zsh/custom}/plugins/zsh-completions",
          }

    # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/kube-ps1
    - name: omz - kube-ps1 plugin
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/kube-ps1/kube-ps1.plugin.zsh
        dest: /home/{{ remote_regular_user }}/.oh-my-zsh/plugins/kube-ps1/
        mode: "774"
