---
- name: zsh - Instalar y setear por default
  block:
    - name: zsh - Instalar
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - zsh
          - fonts-powerline

    - name: zsh - Set as default
      become: true
      shell: chsh -s $(which zsh) "{{ remote_regular_user }}"
  tags: zsh

- name: omz y plugins varios
  tags: omz
  block:
    # https://github.com/ohmyzsh/ohmyzsh
    - name: omz - Descargar script
      become_user: "{{ remote_regular_user }}"
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/omz_install.sh
        mode: "+x"
        force: true

    - name: omz - Instalar
      become_user: "{{ remote_regular_user }}"
      script: /tmp/omz_install.sh --force

    # https://github.com/atuinsh/atuin
    - name: Download Atuin install script
      get_url:
        url: https://raw.githubusercontent.com/atuinsh/atuin/main/install.sh
        dest: /tmp/atuin_install.sh
        mode: "0755"
        force: true
      check_mode: no

    - name: Install Atuin
      become_user: "{{ remote_regular_user }}"
      shell: /tmp/atuin_install.sh --force --git atuinsh/atuin
      args:
        executable: /bin/bash

    - name: omz - Clonar varios plugins
      git:
        repo: "{{ item.key }}"
        dest: "{{ item.value }}"
        clone: yes
        update: yes
      with_items:
        - {
            key: "https://github.com/zsh-users/zsh-syntax-highlighting.git",
            value: "/home/{{ remote_regular_user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting",
          }
        - {
            key: "https://github.com/zsh-users/zsh-autosuggestions",
            value: "/home/{{ remote_regular_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions",
          }
        - {
            key: "https://github.com/zsh-users/zsh-completions",
            value: "/home/{{ remote_regular_user }}/.oh-my-zsh/custom/plugins/zsh-completions",
          }
        - {
            key: "https://github.com/ocadaruma/zsh-gcloud-prompt.git",
            value: "/home/{{ remote_regular_user }}/.oh-my-zsh/custom/plugins/zsh-gcloud-prompt",
          }

    # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/kube-ps1
    - name: omz - Crear directorio kube-ps1
      file:
        path: /home/{{ remote_regular_user }}/.oh-my-zsh/custom/plugins/kube-ps1/
        state: directory
        mode: "0775"
        owner: "{{ remote_regular_user }}"
        group: "{{ remote_regular_user }}"

    - name: omz - kube-ps1 plugin
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/kube-ps1/kube-ps1.plugin.zsh
        dest: /home/{{ remote_regular_user }}/.oh-my-zsh/custom/plugins/kube-ps1/
        mode: "0774"

    - name: zsh - Copiar archivo de configuración
      copy:
        src: /home/{{ remote_regular_user }}/repositorios/ansible_notebooks/roles/sysadmin/files/.zshrc
        dest: /home/{{ remote_regular_user }}/.zshrc
        owner: "{{ remote_regular_user }}"
        group: "{{ remote_regular_user }}"
        mode: "0644"

    - name: zsh - Recargar configuración de zsh
      shell: source /home/{{ remote_regular_user }}/.zshrc
      args:
        executable: /bin/zsh
      become_user: "{{ remote_regular_user }}"
      changed_when: false
