- name: Adhoccli | Configurar repositorio e instalar adhoccli
  tags: adhoccli
  become: true
  block:
    - name: Adhoccli | Asegurar prerrequisitos para repositorios APT
      ansible.builtin.apt:
        name:
          - gnupg
          - apt-transport-https
        state: present

    - name: Adhoccli | Descargar la clave GPG de Adhoc a un archivo temporal
      ansible.builtin.get_url:
        url: https://apt.dev-adhoc.com/adhoc-devops.asc
        dest: /tmp/adhoc-devops.asc
        mode: '0644'

    - name: Adhoccli | Desarmar la clave GPG y colocarla en su ubicación final
      ansible.builtin.command:
        cmd: gpg --dearmor -o /usr/share/keyrings/adhoc-devops.gpg /tmp/adhoc-devops.asc
        creates: "/usr/share/keyrings/adhoc-devops.gpg"
      changed_when: false

    - name: Adhoccli | Limpiar el archivo temporal de la clave GPG
      ansible.builtin.file:
        path: /tmp/adhoc-devops.asc
        state: absent

    - name: Adhoccli | Añadir el repositorio de Adhoc
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/adhoc-devops.gpg] https://apt.dev-adhoc.com/ stable main"
        state: present
        filename: adhoc
        update_cache: true

    - name: Adhoccli | Instalar la herramienta 'adhoccli'
      ansible.builtin.apt:
        name: adhoccli
        state: present
