---
- name: Branding | Copiar archivos de fondo de pantalla
  tags: branding
  become: true
  become_user: "{{ remote_regular_user }}"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: "0644"
  loop: "{{ branding_files_to_copy }}"

- name: Branding | Aplicar configuraciones de fondo de pantalla y protector
  tags: branding
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ branding_dconf_settings }}"
