---
- name: GNOME | Aplicar configuraciones de dconf para el usuario
  tags: ext, gnome, dconf
  become: true
  become_user: "{{ remote_regular_user }}" # Usamos la variable consistente
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ dconf_settings }}" # Usamos la sintaxis moderna 'loop'
