---
# Add Fav Apps
- name: Fixes - varios
  tags: funcional_fixes
  block:
    - name: Fixes - Agregar apps al panel lateral
      when: ansible_facts['distribution'] == 'Ubuntu'
      become_method: sudo
      become_user: "{{ lookup('env', 'USER') }}"
      community.general.dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "['google-chrome.desktop', 'org.gnome.Nautilus.desktop','org.gnome.Terminal.desktop','org.gnome.Flameshot.desktop']"

    # Para desactivar el minimize to click:
    # gsettings reset org.gnome.shell.extensions.dash-to-dock click-action
    - name: Fixes - Minimize to click
      when: ansible_facts['distribution'] == 'Ubuntu'
      become_method: sudo
      become_user: "{{ lookup('env', 'USER') }}"
      community.general.dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/click-action"
        value: "'minimize'"
        state: present

    - name: Fixes - Copiar archivo .bashrc
      ansible.builtin.copy:
        src: files/.bashrc
        dest: /home/{{ remote_regular_user }}/.bashrc
        owner: "{{ remote_regular_user }}"
        group: "{{ remote_regular_user }}"
        mode: "774"

- name: Fixes - xorg
  tags: xorg_fixes
  block:
    - name: Fixes - Reinstalar xorg
      become: true
      ansible.builtin.command: apt-get install --reinstall -y xorg

    - name: Fixes - Configurar GDM3 para forzar uso de Xorg
      become: true
      ansible.builtin.blockinfile:
        path: /etc/gdm3/custom.conf
        marker: "# {mark} ANSIBLE XORG FIX"
        block: |
          WaylandEnable=false
          DefaultSession=gnome-xorg.desktop
        insertafter: '^\[daemon\]'
        state: present
