---
- name: Arreglos | Aplicar aplicaciones favoritas del dock (todas las distros)
  tags: funcional_fixes, gnome
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "{{ funcional_gnome_functional_favorite_apps }}"
    state: present
  when: not (skip_gnome_tasks | default(false))
