---
- name: Arreglos | Aplicar personalizaciones de GNOME y del dock
  tags: funcional_fixes, gnome
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { key: "/org/gnome/shell/favorite-apps", value: "{{ gnome_favorite_apps }}" }
    - { key: "/org/gnome/shell/extensions/dash-to-dock/click-action", value: "'minimize'" }
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Arreglos | Reinstalar Xorg (solo si se solicita explícitamente)
  tags: xorg_fixes
  become: true
  ansible.builtin.apt:
    name: xorg
    state: present
    reinstall: yes
  when: force_xorg_reinstall | bool

- name: Arreglos | Configurar GDM3 para forzar el uso de Xorg
  tags: xorg_fixes
  become: true
  ansible.builtin.blockinfile:
    path: /etc/gdm3/custom.conf
    marker: "# {mark} ANSIBLE XORG FIX"
    block: |
      WaylandEnable=false
      DefaultSession=gnome-xorg.desktop
    insertafter: '^\[daemon\]'
    state: present
  notify: Restart GDM
