- name: Arreglos | Forzar Xorg y reinstalar (Solo para Ubuntu 22.04)
  tags: xorg_fixes
  become: true
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - ansible_facts['distribution_version'] == '22.04'
  block:
    - name: Arreglos | Reinstalar Xorg (controlado por variable)
      ansible.builtin.apt:
        name: xorg
        state: present
        force: true
      when: force_xorg_reinstall | bool

    - name: Arreglos | Configurar GDM3 para forzar el uso de Xorg
      ansible.builtin.blockinfile:
        path: /etc/gdm3/custom.conf
        marker: "# {mark} ANSIBLE XORG FIX"
        block: |
          WaylandEnable=false
          DefaultSession=gnome-xorg.desktop
        insertafter: '^\[daemon\]'
        state: present
