---
# Add Fav Apps
- name: Fixes - Agregar apps al panel lateral
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['google-chrome.desktop', 'org.gnome.Nautilus.desktop','org.gnome.Terminal.desktop','org.gnome.Flameshot.desktop']"

# Make Nautilus capable of browse recursively
- name: Fixes - Agregar repositorio para nautilus
  become: true
  apt_repository:
    repo: ppa:lubomir-brindza/nautilus-typeahead

- name: Fixes - Actualizar nautilus a latest
  become: true
  apt:
    name: nautilus
    state: present
    update_cache: true

- name: Fixes - Enable nautilus location & interactive search
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - {
        key: "/org/gnome/nautilus/preferences/always-use-location-entry",
        value: "true",
      }
    - {
        key: "/org/gnome/nautilus/preferences/enable-interactive-search",
        value: "true",
      }

- name: Fixes - Minimize to click
  become_user: "{{ remote_regular_user }}"
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/click-action"
    value: "'minimize'"
    state: present
