---
- name: Paquetes | Instalar todos los paquetes necesarios
  tags: packages_funcional
  vars:
    all_packages_to_install: >-
      {{ packages_system +
         packages_compression +
         packages_apps +
         packages_hardware_analysis +
         packages_gui_utils }}

    excluded_packages: >-
      {{ packages_exclude_debian_13 if ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == '13' else [] }}

  ansible.builtin.apt:
    name: "{{ all_packages_to_install | difference(excluded_packages) }}"
    state: present
