---
- name: Paquetes - Instalación varios
  tags: packages_funcional
  block:
    - name: Base - Eliminar programas sin uso
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - thunderbird
          - rhythmbox
          - remmina
