---
- name: Paquetes - Instalación varios
  tags: packages_funcional
  ansible.builtin.apt:
    # Concatenamos todas las listas de paquetes en una sola.
    name: "{{ packages_system + packages_compression + packages_apps + packages_hardware_analysis + packages_gui_utils + python_for_functionals}}"
    state: present

- name: Paquetes | Instalar paquetes específicos de Ubuntu
  tags: packages_funcional
  ansible.builtin.apt:
    name: "{{ packages_ubuntu_only }}"
    state: present
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Paquetes | Eliminar programas no deseados
  tags: packages_funcional
  ansible.builtin.apt:
    name: "{{ packages_to_remove }}"
    state: absent
