---
# Usuario genérico para ejecutar algunas tareas
remote_regular_user: "{{ ansible_env.SUDO_USER | default(ansible_user) }}"
remote_regular_user_uid: "{{ ansible_user_uid }}"

# Lista de paquetes base para el perfil de DEV
devs_packages_base:
  - ccze
  - tmux
  - tmuxp
  - xclip
  - bash-completion
  - yakuake
  - vim
  - gnupg
  - meld
  - xz-utils

# Lista de paquetes de Docker y sus componentes
devs_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin # El plugin moderno para 'docker compose'

# Prerrequisitos para añadir el repositorio de Docker
devs_docker_prerequisites:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

# Configuraciones de dconf para Meld
devs_meld_dconf_settings:
  - { key: "/org/gnome/meld/indent-width", value: "4" }
  - { key: "/org/gnome/meld/insert-spaces-instead-of-tabs", value: "true" }
  - { key: "/org/gnome/meld/highlight-syntax", value: "true" }
  - { key: "/org/gnome/meld/draw-spaces", value: "['space', 'tab', 'newline', 'nbsp', 'leading', 'text', 'trailing']" }
  - { key: "/org/gnome/meld/show-line-numbers", value: "true" }
  - { key: "/org/gnome/meld/highlight-current-line", value: "true" }
  - { key: "/org/gnome/meld/wrap-mode", value: "'word'" }
  - { key: "/org/gnome/meld/vc-commit-margin", value: "80" }
  - { key: "/org/gnome/meld/text-filters", value: "('All whitespace', true, '[ \\\\t\\\\r\\\\f\\\\v]*')" }

# Lista de archivos de configuración para VS Code
devs_vscode_config_files:
  - { src: "settings.json", dest: ".config/Code/User/settings.json" }
  - { src: "keybindings.json", dest: ".config/Code/User/keybindings.json" }
  - { src: "pycodestyle", dest: ".config/pycodestyle" }
  - { src: "flake8", dest: ".config/flake8" }

# Extensiones predefinidas para devs
devs_vscode_extension_list:
  # Install Visual Studio Code extensions.
  - ms-python.python
  # Supercharge the Git capabilities built into Visual Studio Code
  - eamodio.gitlens
  # Odoo snippets
  - mstuttgart.odoo-snippets
  # Check spell (En & Es)
  - streetsidesoftware.code-spell-checker
  - streetsidesoftware.code-spell-checker-spanish
  # Odoo IDE (https://marketplace.visualstudio.com/items?itemName=trinhanhngoc.vscode-odoo)
  - trinhanhngoc.vscode-odoo
  # Kubernetes extension
  - ms-kubernetes-tools.vscode-kubernetes-tools
  # Remote development
  - ms-vscode-remote.vscode-remote-extensionpack

# Paquetes de sistema para el entorno de Python
devs_python_packages:
  - ipython3
  - python3-setuptools
  - python3-pip
  - pylint
  - python3
  - "{{ 'python3.10-venv' if ansible_facts['distribution_version'] == '22.04' else
       ('python3.12-venv' if ansible_facts['distribution_version'] == '24.04' else
       'python3-venv') }}"

# Ruta para el entorno virtual de los linters
devs_python_venv_path: "/home/{{ remote_regular_user }}/python-venvs/linters"

# Paquetes a instalar con pip dentro del entorno virtual
devs_python_linter_packages:
  - pylint-odoo
  - flake8
  - pep8
  - pre-commit

# Repositorio con los hooks de git
devs_hooks_repo_url: "https://github.com/OCA/maintainer-quality-tools"
devs_hooks_repo_path: "/home/{{ remote_regular_user }}/repositorios/maintainer-quality-tools"

# Ruta para los hooks de Git globales
devs_git_hooks_path: "/home/{{ remote_regular_user }}/.git_hooks"

# Lista de configuraciones para el .gitconfig global del usuario
devs_git_config_settings:
  - { name: core.editor, value: code --wait }
  - { name: diff.tool, value: default-difftool }
  - { name: difftool.default-difftool.cmd, value: code --wait --diff $LOCAL $REMOTE }
  - { name: push.default, value: nothing }
  - { name: pull.ff, value: only }
  - { name: core.hooksPath, value: "{{ devs_git_hooks_path }}" }
  - { name: alias.lg, value: log --oneline --graph --decorate }
  - { name: alias.co, value: checkout }
  - { name: alias.ci, value: commit }
  - { name: alias.st, value: status }
  - { name: alias.amend, value: commit --amend --no-edit }
  - { name: alias.unstage, value: reset HEAD -- }
  - { name: alias.undo, value: reset --soft HEAD^ }
  - { name: alias.lol, value: log --oneline --decorate }
  - { name: alias.graph, value: log --oneline --graph --decorate }
  - { name: alias.reflog, value: reflog --oneline --date=iso --decorate }
  - { name: alias.diffw, value: diff --word-diff --ignore-all-space }

# Lista de hooks genéricos que apuntan al mismo script
devs_git_generic_hook_list:
  - applypatch-msg
  - commit-msg
  - fsmonitor-watchman
  - post-update
  - pre-applypatch
  - pre-commit
  - pre-rebase
  - pre-receive
  - prepare-commit-msg
  - update

# Prerrequisitos para añadir el repositorio de Kubernetes
devs_kubectl_prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl

# --- Configuración de Rancher CLI ---
devs_rancher_cli_repo: "rancher/cli"

# Lista de aplicaciones favoritas para el perfil de DEV
devs_gnome_favorite_apps: "['google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'org.kde.yakuake.desktop', 'org.gnome.Terminal.desktop', 'code.desktop']"

# --- Configuración del Entorno de Desarrollo Odoo ---
devs_odoo_base_path: "/home/{{ remote_regular_user }}/odoo"
devs_odoo_ctx_repo: "https://github.com/ingadhoc/docker-compose-context.git"
devs_odoo_main_repo: "https://github.com/ingadhoc/docker-compose-odoo.git"

devs_ssh_config:
  key_path: "/home/{{ remote_regular_user }}/.ssh/id_rsa_{{ remote_regular_user }}@{{ ansible_hostname }}"
  key_type: "rsa"
  key_size: 4096
  config_template_src: "sshconfig.j2"
