---
- name: Visual Studio Code - Descargar e instalar
  apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
  when: ansible_userspace_architecture == 'x86_64'

- name: Instalar muchas extensiones predefinidas
  become_user: "{{ remote_regular_user }}"
  command: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extension_list_devs }}"
  changed_when: False

- name: Visual Studio Code - Definir como editor de texto predeterminado
  become_user: "{{ remote_regular_user }}"
  command: "xdg-mime default code.desktop application/x-shellscript text/plain text/markdown application/x-yaml text/x-python"

- name: Visual Studio Code - Configuraciones y personalizaciones
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: 666
  with_items:
    - { src: ./files/settings.json, dest: ~/.config/Code/User/ }
    - { src: ./files/keybindings.json, dest: ~/.config/Code/User/ }
    - { src: ./files/pycodestyle, dest: ~/.config/ }
    - { src: ./files/flake8, dest: ~/.config/ }
