---
- name: Code | Añadir el repositorio oficial y el paquete de VS Code
  tags: code
  become: true
  block:
    - name: Code | Añadir la clave GPG de Microsoft
      ansible.builtin.shell: >
        curl -fsSL https://packages.microsoft.com/keys/microsoft.asc |
        gpg --dearmor -o /etc/apt/keyrings/packages.microsoft.gpg
      args:
        creates: /etc/apt/keyrings/packages.microsoft.gpg
      changed_when: false

    - name: Code | Añadir el repositorio de VS Code
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
        state: present
        filename: vscode
        update_cache: true

    - name: Code | Instalar el paquete 'code'
      ansible.builtin.apt:
        name: code
        state: present

- name: Code | Gestionar extensiones de forma idempotente
  tags: code
  become: true
  become_user: "{{ remote_regular_user }}"
  block:
    - name: Code | Obtener lista de extensiones ya instaladas
      ansible.builtin.command: "code --list-extensions"
      environment:
        DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ remote_regular_user_uid }}/bus"
      register: installed_extensions
      changed_when: false

    - name: Code | Instalar solo las extensiones que falten
      ansible.builtin.command: "code --install-extension {{ item }}"
      loop: "{{ vscode_extension_list_devs }}"
      when: item not in installed_extensions.stdout_lines

- name: Code | Gestionar la configuración del usuario
  tags: code
  become: true
  become_user: "{{ remote_regular_user }}"
  block:
    - name: Code | Establecer como editor por defecto para ciertos tipos de archivo
      ansible.builtin.command: "xdg-mime default code.desktop application/x-shellscript text/plain text/markdown application/x-yaml text/x-python"
      changed_when: false

    - name: Code | Crear directorios de configuración en el home del usuario
      ansible.builtin.file:
        path: "/home/{{ remote_regular_user }}/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - ".config/Code/User"
        - ".config/pycodestyle"
        - ".config/flake8"

    - name: Code | Copiar archivos de configuración
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/home/{{ remote_regular_user }}/{{ item.dest }}"
        owner: "{{ remote_regular_user }}"
        group: "{{ remote_regular_user }}"
        mode: "0644"
      loop: "{{ dev_vscode_config_files }}"
