---
- name: Visual Studio Code - Install and Configure
  tags: code
  block:
    - name: Code - Ensure old or corrupt GPG key is removed
      become: true
      ansible.builtin.file:
        path: /etc/apt/keyrings/packages.microsoft.gpg
        state: absent

    - name: Code - Download Microsoft GPG key (ASCII) to a temporary file
      become: true
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /tmp/microsoft.asc
        mode: '0644'

    - name: Code - Dearmor GPG key to binary format
      become: true
      ansible.builtin.shell:
        cmd: gpg --dearmor -o /etc/apt/keyrings/packages.microsoft.gpg /tmp/microsoft.asc

    - name: Code - Add VS Code APT repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main"
        state: present
        filename: vscode
        update_cache: true

    - name: Code - Remove temporary GPG key file
      become: true
      ansible.builtin.file:
        path: /tmp/microsoft.asc
        state: absent

    - name: Code - Install Visual Studio Code
      become: true
      ansible.builtin.apt:
        name: code
        state: present
      when: ansible_userspace_architecture == 'x86_64'

    - name: Code - Install predefined extensions
      become: true
      ansible.builtin.shell: "su - {{ lookup('env', 'USER') }} -c 'code --install-extension {{ item }}'"
      with_items: "{{ vscode_extension_list_devs }}"
      changed_when: false

    - name: Code - Set as default text editor
      become: true
      ansible.builtin.shell: "su - {{ lookup('env', 'USER') }} -c 'xdg-mime default code.desktop application/x-shellscript text/plain text/markdown application/x-yaml text/x-python'"
      changed_when: false

    - name: Code - Create configuration directories
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - ".config"
        - ".config/Code"
        - ".config/Code/User"

    - name: Code - Copy configuration files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: "0644"
      with_items:
        - { src: ./files/settings.json, dest: .config/Code/User/settings.json }
        - { src: ./files/keybindings.json, dest: .config/Code/User/keybindings.json }
        - { src: ./files/pycodestyle, dest: .config/pycodestyle }
        - { src: ./files/flake8, dest: .config/flake8 }
