---
- name: Visual Studio Code - Instalar y configurar
  tags: code
  block:
    - name: Descargar y agregar clave GPG de Microsoft al keyring de APT
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /usr/share/keyrings/microsoft-vscode-archive-keyring.gpg
        mode: '0644'
        force: true # Asegura que el archivo se descargue incluso si ya existe
      register: vscode_key_download # Registra el resultado para usarlo en el siguiente paso

    - name: Agregar repositorio de Visual Studio Code
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-vscode-archive-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main"
        state: present
        filename: vscode # Opcional: Nombre del archivo .list en sources.list.d/
      when: ansible_userspace_architecture == 'x86_64'

    - name: Actualizar la caché de paquetes
      ansible.builtin.apt:
        update_cache: yes

    - name: Instalar Visual Studio Code
      ansible.builtin.apt:
        name: code
        state: present
      when: ansible_userspace_architecture == 'x86_64'

    - name: Instalar muchas extensiones predefinidas
      become: true
      ansible.builtin.shell: "su - {{ lookup('env', 'USER') }} -c 'code --install-extension {{ item }}'"
      with_items: "{{ vscode_extension_list_devs }}"
      changed_when: false

    - name: Visual Studio Code - Definir como editor de texto predeterminado
      become: true
      ansible.builtin.shell: "su - {{ lookup('env', 'USER') }} -c 'xdg-mime default code.desktop application/x-shellscript text/plain text/markdown application/x-yaml text/x-python'"
      changed_when: false

    - name: Crear directorios necesarios para configuraciones
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - ".config"
        - ".config/Code"
        - ".config/Code/User"

    - name: Visual Studio Code - Configuraciones y personalizaciones
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: "0644"
      with_items:
        - { src: ./files/settings.json, dest: .config/Code/User/settings.json }
        - { src: ./files/keybindings.json, dest: .config/Code/User/keybindings.json }
        - { src: ./files/pycodestyle, dest: .config/pycodestyle }
        - { src: ./files/flake8, dest: .config/flake8 }
