---
- name: Include vars
  ansible.builtin.include_vars: "{{ role_path }}/vars.yml"
  tags: devs
  no_log: true

- name: Include
  block:
    - name: Packages
      ansible.builtin.import_tasks: packages_dev.yml
    - name: Warp
      ansible.builtin.import_tasks: warp_terminal.yml
    - name: Docker
      ansible.builtin.import_tasks: docker.yml
    - name: Meld
      ansible.builtin.import_tasks: meld.yml
    - name: Code
      ansible.builtin.import_tasks: code.yml
    - name: Python
      ansible.builtin.import_tasks: python.yml
    - name: Git
      ansible.builtin.import_tasks: git.yml
    - name: Kubectl
      ansible.builtin.import_tasks: kubectl.yml
    - name: Rancher2
      ansible.builtin.import_tasks: rancher2.yml
    - name: Fixes
      ansible.builtin.import_tasks: fixes.yml
    - name: Prepare RemoteDev
      ansible.builtin.import_tasks: prepare_remote_dev.yml
    - name: Ssh
      ansible.builtin.import_tasks: ssh.yml
    - name: GH
      ansible.builtin.import_tasks: gh_cli.yml
