---
- include_vars: ./roles/vars.yml
  tags: devs

- block:
    - import_tasks: packages_dev.yml
    - import_tasks: code.yml
    - import_tasks: python.yml
    - import_tasks: git.yml
    - import_tasks: kubectl.yml
    - import_tasks: rancher2.yml
    - import_tasks: fixes.yml
    - import_tasks: prepare_dev.yml
    - import_tasks: ssh.yml
    - import_tasks: docker.yml
