---
- name: Meld | Aplicar configuraciones de la herramienta de comparación
  tags: meld
  become: true
  become_user: "{{ remote_regular_user }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ devs_meld_dconf_settings }}"
