---
- name: Editor de texto, colorizer, terminal
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - vim-gtk3
      - ccze
      - tmux
      - tmuxp
      - xclip
      - bash-completion
      - yakuake

- name: Yakuake - Configuraciones
  become_user: "{{ remote_regular_user }}"
  copy:
    src: ./files/yakuakerc
    dest: ~/.config/
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: '0666'

- name: Yakuake - Directorio para configuración
  file:
    path: ~/.local/share/konsole
    state: directory
    mode: "774"

- name: Yakuake - Copiar archivo configuración
  copy:
    src: ./files/Profile_1.profile
    dest: ~/.local/share/konsole
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: "0666"
