---
- name: Devs - Instalación paquetes varios
  tags: packages_dev
  block:
    - name: Editor de texto, colorizer, terminal
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - ccze
          # - tmux
          - tmuxp
          - xclip
          # - bash-completion
          - yakuake

- name: Yakuake - Instalación y configuración
  tags: yakuake
  block:
    - name: Yakuake - Configuraciones
      become_method: sudo
      become_user: "{{ lookup('env','USER') }}"
      copy:
        src: ./files/yakuakerc
        dest: ~/.config/
        owner: "{{ remote_regular_user }}"
        group: "{{ remote_regular_user }}"
        mode: "0666"

    - name: Yakuake - Directorio para configuración
      file:
        path: ~/.local/share/konsole
        state: directory
        mode: "774"

    - name: Yakuake - Copiar archivo configuración
      copy:
        src: ./files/Profile_1.profile
        dest: ~/.local/share/konsole
        owner: "{{ remote_regular_user }}"
        group: "{{ remote_regular_user }}"
        mode: "0666"
