---
- name: Python | Instalar paquetes de sistema para el entorno de desarrollo
  tags: python
  become: true
  ansible.builtin.apt:
    name: "{{ devs_python_packages }}"
    state: present
    update_cache: true

- name: Python | Gestionar entorno virtual y herramientas de linting
  tags: python
  become: true
  become_user: "{{ remote_regular_user }}"
  block:
    - name: Python | Crear directorio para entornos virtuales
      ansible.builtin.file:
        path: "/home/{{ remote_regular_user }}/python-venvs"
        state: directory
        mode: "0755"

    - name: Python | Crear entorno virtual para linters
      ansible.builtin.command: "python3 -m venv {{ devs_python_venv_path }}"
      args:
        creates: "{{ devs_python_venv_path }}/bin/pip"

    - name: Python | Instalar herramientas de linting en el entorno virtual
      ansible.builtin.pip:
        executable: "{{ devs_python_venv_path }}/bin/pip"
        name: "{{ devs_python_linter_packages }}"
        state: present

- name: Tools | Clonar repositorio de odoo_log_analyser
  tags: odoo_tools
  become: true
  become_user: "{{ remote_regular_user }}"
  ansible.builtin.git:
    repo: https://github.com/adhoc-dev/odoo_log_analyser.git
    dest: "/home/{{ remote_regular_user }}/repositorios/odoo_log_analyser"
    version: main
