---
- name: Descargar binario y extraer
  unarchive:
    src: https://github.com/rancher/cli/releases/download/v0.6.13/rancher-linux-amd64-v0.6.13.tar.gz
    dest: /tmp
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: "744"
    remote_src: true

- name: Mover binario al path
  copy:
    src: /tmp/rancher-v0.6.13/rancher
    dest: /usr/local/bin/rancher
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
    mode: "744"
