---
- name: Rancher CLI | Instalar o actualizar usando script dedicado
  tags: rancher
  become: true
  block:
    - name: Rancher CLI | Copiar el script de instalación al equipo
      ansible.builtin.copy:
        src: install_rancher_cli.sh
        dest: /tmp/install_rancher_cli.sh
        mode: '0755'

    - name: Rancher CLI | Ejecutar el script de instalación
      # El script se encarga de la idempotencia y las actualizaciones.
      ansible.builtin.command: /tmp/install_rancher_cli.sh
      register: devs_rancher_install_script_result
      # La tarea reporta un cambio solo si el script realmente instaló o actualizó algo.
      changed_when: "'Descargando' in devs_rancher_install_script_result.stdout"

    - name: Rancher CLI | Crear enlace simbólico 'rancher2' para compatibilidad
      ansible.builtin.file:
        src: /usr/local/bin/rancher
        dest: /usr/local/bin/rancher2
        state: link
        force: true
