---
- name: Rancher2 - Instalación
  tags: rancher
  block:
    - name: Rancher2 - Descargar binario y extraer
      unarchive:
        src: https://github.com/rancher/cli/releases/download/{{ rancher2_version }}/rancher-linux-amd64-{{ rancher2_version }}.tar.xz
        dest: /tmp
        owner: "{{ remote_regular_user }}"
        group: "{{ remote_regular_user }}"
        mode: "774"
        remote_src: true

    - name: Rancher2 - Mover binario al path
      copy:
        src: /tmp/rancher-{{ rancher2_version }}/rancher
        dest: /usr/local/bin/rancher2
        owner: "{{ remote_regular_user }}"
        group: "{{ remote_regular_user }}"
        mode: "774"

    - name: Rancher2 - Eliminar directorio temporal
      file:
        path: /tmp/rancher-{{ rancher2_version }}
        state: absent
