---
- name: Rancher CLI | Instalar o actualizar la CLI de Rancher
  tags: rancher
  become: true
  block:
    - name: Rancher CLI | Verificar la versión instalada (si existe)
      ansible.builtin.command: "rancher --version"
      register: devs_rancher_current_version
      changed_when: false
      ignore_errors: true

    - name: Rancher CLI | Obtener información de la última versión desde GitHub
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{ devs_rancher_cli_repo }}/releases/latest"
        return_content: true
      register: devs_rancher_latest_release

    - name: Rancher CLI | Definir y comparar las versiones
      ansible.builtin.set_fact:
        devs_current_version: >-
          {{ devs_rancher_current_version.stdout |
             regex_search('v([0-9]+\\.[0-9]+\\.[0-9]+)') |
             replace('v', '') if devs_rancher_current_version.rc == 0 else '0.0.0' }}
        devs_latest_version: "{{ devs_rancher_latest_release.json.tag_name | replace('v', '') }}"

    - name: Rancher CLI | Instalar o actualizar si es necesario
      when: devs_current_version != devs_latest_version
      block:
        - name: "Rancher CLI | Descargando e instalando versión {{ devs_latest_version }}"
          vars:
            download_url: >-
              {{ devs_rancher_latest_release.json |
                 json_query("assets[?contains(name, 'linux-amd64') && ends_with(name, '.tar.gz')].browser_download_url | [0]") }}
          ansible.builtin.unarchive:
            remote_src: true
            src: "{{ download_url }}"
            dest: "/usr/local/bin/"
            extra_opts:
              - "--strip-components=1"
            owner: root
            group: root
            mode: "0755"

    - name: Rancher CLI | Crear enlace simbólico 'rancher2' para compatibilidad
      ansible.builtin.file:
        src: /usr/local/bin/rancher
        dest: /usr/local/bin/rancher2
        state: link
        force: true

    - name: Rancher CLI | Añadir autocompletado de bash para el usuario
      become: true
      become_user: "{{ remote_regular_user }}"
      ansible.builtin.blockinfile:
        path: "/home/{{ remote_regular_user }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - RANCHER COMPLETION"
        block: |
          if command -v rancher >/dev/null 2>&1; then
            source <(rancher completion bash)
          fi
