---
- name: Rancher2 - Instalación
  tags: rancher
  block:
    - name: Rancher2 - Descargar binario y extraer
      block:
        - name: Get Last Version URL
          ansible.builtin.uri:
            url: https://api.github.com/repos/rancher/cli/releases/latest
            return_content: true
          register: json_response

        - name: Download and Install
          loop: "{{ json_response.json.assets }}"
          when:
            - item.name is search("^rancher-linux-amd64")
            - item.name is search("tar.xz$")
          ansible.builtin.unarchive:
            remote_src: true
            src: "{{ item.browser_download_url }}"
            dest: /tmp

        - name: Rancher2 - Mover binario al path
          become: true
          ansible.builtin.copy:
            src: /tmp/rancher-{{ json_response.json.tag_name }}/rancher
            dest: /usr/local/bin/rancher
            mode: "0755"

        - name: Create symbolic link
          ansible.builtin.file:
            src: /usr/local/bin/rancher
            dest: /usr/local/bin/rancher2
            state: link

        - name: Rancher2 - Eliminar directorio temporal
          ansible.builtin.file:
            path: /tmp/rancher-{{ json_response.json.tag_name }}
            state: absent

        # - name: Add bash completion
        #   ansible.builtin.blockinfile:
        #     path: /home/{{ remote_regular_user }}/.bashrc
        #     block: |
        #       if command -v rancher >/dev/null 2>&1; then
        #         source <(rancher completion bash)
        #       fi
