---
- name: Warp | Instalar Warp Terminal
  tags: warp
  become: true
  block:
    - name: Warp | Añadir la clave GPG del repositorio
      ansible.builtin.get_url:
        url: "{{ devs_warp_gpg_url }}"
        dest: "{{ devs_warp_gpg_path }}"
        mode: '0644'

    - name: Warp | Añadir el repositorio de APT
      ansible.builtin.apt_repository:
        repo: "{{ devs_warp_repo_line }}"
        state: present
        filename: warp
        update_cache: true

    - name: Warp | Instalar el paquete 'warp-terminal'
      ansible.builtin.apt:
        name: "{{ devs_warp_package }}"
        state: present
